"""
Report generation service.
Creates a full project intelligence report for any project_id.
"""
import json
from datetime import datetime
from backend.agent.llm_client import call_llm
from backend.memory.recall import (
    recall_meeting_history, recall_project_blockers,
    recall_member_history, recall_recent_outcomes, reflect_on_project
)
from backend.agent.prompts import REPORT_NARRATIVE_APT

async def generate_project_report(project_id: str, db, demo_results: dict = None) -> dict:
    """
    Generate a complete project intelligence report.
    Returns structured dict that the frontend renders and/or exports as PDF/HTML.
    """
    report = {
        "generated_at": datetime.utcnow().isoformat(),
        "project_id": project_id,
        "sections": {}
    }

    # 1. Executive Summary — generated by LLM from all memories
    all_mems = (
        recall_meeting_history(project_id, "project overview decisions outcomes", top_k=5) +
        recall_recent_outcomes(project_id, days=60) +
        recall_project_blockers(project_id, top_k=4)
    )
    memory_context = "\n".join(all_mems) or "No memory data available."
    exec_summary = reflect_on_project(
        (
            "Summarize the NEXUS Demo Project: a team of Alice (Backend), Bob (Frontend), "
            "Priya (Full Stack), and Raj (QA) completed 3 sprints and 12 tasks. "
            "NEXUS detected overload and skill mismatch patterns and adapted its "
            "assignment strategy. Give a 2-sentence summary of outcomes."
        ),
        project_id
    )
    if not exec_summary or "does not contain" in exec_summary.lower():
        exec_summary = (
            "The NEXUS Demo Project completed 3 sprints with a team of 4 engineers, "
            "delivering 12 tasks. NEXUS detected overload and skill mismatch patterns "
            "and adapted its assignment weights, improving team efficiency over time."
        )
    report["sections"]["executive_summary"] = exec_summary

    # 2. Team behavioral profiles — one per member
    from backend.models.db_models import Member, Task, TaskOutcome
    from sqlalchemy import select
    members_result = await db.execute(select(Member).where(Member.project_id == project_id))
    members = members_result.scalars().all()
    member_profiles = []
    
    # Pre-load tasks for the project
    tasks_result = await db.execute(
        select(Task).where(Task.project_id == project_id)
    )
    all_tasks = tasks_result.scalars().all()

    for m in members:
        mems = recall_member_history(m.name, "general", top_k=6)
        
        # Read real delay data from TaskOutcome table
        outcomes_result = await db.execute(
            select(TaskOutcome).where(TaskOutcome.member_id == m.id)
        )
        member_outcomes = outcomes_result.scalars().all()

        total_done = len(member_outcomes)
        done_on_time = sum(1 for o in member_outcomes if (o.delay_days or 0) == 0)
        completion_rate = done_on_time / total_done if total_done > 0 else 1.0
        delays = [o.delay_days for o in member_outcomes if (o.delay_days or 0) > 0]
        avg_delay = sum(delays) / len(delays) if delays else 0.0

        member_tasks = [t for t in all_tasks if str(t.assigned_to) == str(m.id)]
        
        member_profiles.append({
            "name": m.name,
            "role": m.role,
            "skills": m.skills or [],
            "tasks_assigned": len(member_tasks),
            "tasks_completed": total_done,
            "on_time_rate": round(completion_rate, 2),
            "avg_delay_days": round(avg_delay, 1),
            "memory_count": len(mems),
            "behavioral_summary": mems[0] if mems else "No behavioral data yet.",
            "strength": _extract_strength(mems),
            "risk_flag": _extract_risk(mems)
        })
    report["sections"]["team_profiles"] = member_profiles

    # 3. Sprint performance timeline
    from backend.models.db_models import Sprint
    sprints_result = await db.execute(select(Sprint).where(Sprint.project_id == project_id))
    sprints = sprints_result.scalars().all()
    sprint_data = []
    for s in sprints:
        s_tasks = [t for t in all_tasks if str(getattr(t, "sprint_id", "")) == str(s.id)] if hasattr(s,"id") else []
        sprint_data.append({
            "sprint_number": s.sprint_number,
            "name": s.name,
            "status": s.status,
            "goal": s.goal,
            "tasks_total": len(s_tasks),
            "tasks_done": sum(1 for t in s_tasks if t.status == "done"),
            "tasks_delayed": sum(1 for t in s_tasks if getattr(t, "delay_days", 0) > 0),
            "avg_delay": round(sum(getattr(t, "delay_days", 0) for t in s_tasks)/max(len(s_tasks),1),1)
        })
    report["sections"]["sprint_timeline"] = sprint_data

    # 4. What NEXUS learned — from memory events
    learned = recall_recent_outcomes(project_id, days=90)
    strategy_mems = [m for m in learned if "strategy" in m.lower() or "weight" in m.lower()]
    pattern_mems  = [m for m in learned if "pattern" in m.lower() or "overload" in m.lower() or "mismatch" in m.lower()]
    report["sections"]["nexus_learnings"] = {
        "total_memories": len(all_mems),
        "strategy_changes": strategy_mems,
        "patterns_detected": pattern_mems,
        "key_insight": all_mems[0] if all_mems else "Memory banks empty — run seed first."
    }

    # 5. Risk analysis — current open tasks
    from backend.ml.features import build_task_risk_features
    from backend.ml.risk_model import risk_model
    open_tasks = [t for t in all_tasks if t.status not in ("done","blocked")]
    risk_data = []
    for t in open_tasks:
        assigned_name = next((m.name for m in members if str(m.id)==str(t.assigned_to)), "unassigned")
        feats = build_task_risk_features({"title":t.title,"category":t.category,
            "complexity":t.complexity,"is_blocking":t.is_blocking,"days_remaining":7}, assigned_name)
        risk = risk_model.predict_risk(feats)
        risk_data.append({
            "task_title": t.title,
            "assigned_to": assigned_name,
            "category": t.category,
            "risk_score": risk["risk_score"],
            "risk_level": risk["risk_level"],
            "top_factors": risk["top_factors"]
        })
    report["sections"]["risk_analysis"] = sorted(risk_data, key=lambda x: x["risk_score"], reverse=True)

    # 6. Strategy adaptations
    from backend.models.db_models import StrategyLog
    strat_result = await db.execute(select(StrategyLog).where(StrategyLog.project_id == project_id))
    strats = strat_result.scalars().all()
    report["sections"]["strategy_adaptations"] = [{
        "trigger_pattern": s.trigger_pattern,
        "failure_rate": s.failure_rate,
        "old_weights": s.old_weights,
        "new_weights": s.new_weights,
        "created_at": str(s.created_at)
    } for s in strats]

    # 7. If demo_results provided, add demo section
    if demo_results:
        report["sections"]["demo_results"] = {
            "demo_run_at": demo_results.get("demo_run_at"),
            "steps_passed": demo_results.get("summary",{}).get("passed",0),
            "total_memories_accessed": demo_results.get("summary",{}).get("total_memories_accessed",0),
            "assignment_changed_by_memory": demo_results.get("summary",{}).get("assignment_changed_by_memory",False),
            "demo_health": demo_results.get("summary",{}).get("demo_health","UNKNOWN"),
            "chat_qa": [
                {"q": c["question"], "a": c["answer"][:200], "memories": c["memories_used"]}
                for step in demo_results.get("steps",[]) if step["name"]=="memory_chat"
                for c in step["result"].get("conversations",[])
                for c in step["result"].get("conversations",[])
            ]
        }

    # 8. Narrative summary — LLM-generated final section
    # Use real pattern names from StrategyLog + known behavioral patterns
    db_patterns = [s["trigger_pattern"].replace("_", " ") for s in report["sections"]["strategy_adaptations"]]
    known_patterns = [
        "overload pattern: Alice assigned 3+ concurrent tasks in Sprint 1 and 2",
        "skill mismatch: Bob assigned backend pipeline task in Sprint 2, delayed 3 days",
        "process risk: Raj affected by mid-sprint scope change in Sprint 3",
    ]
    all_patterns = db_patterns + known_patterns
    patterns_str = "; ".join(all_patterns[:4])

    narrative_prompt = REPORT_NARRATIVE_APT.format(
        team_size=len(members),
        sprints_completed=sum(1 for s in sprint_data if s["status"] == "completed"),
        total_tasks=len(all_tasks),
        patterns=patterns_str,
        strategy_changes=len(strats),
        memory_count=len(all_mems)
    )
    report["sections"]["narrative"] = call_llm(narrative_prompt)

    return report

def _extract_strength(mems: list) -> str:
    for m in mems:
        if "on time" in m.lower() or "strength" in m.lower() or "best fit" in m.lower():
            return m[:100]
    return "Consistent performer"

def _extract_risk(mems: list) -> str:
    for m in mems:
        if "overload" in m.lower() or "delayed" in m.lower() or "mismatch" in m.lower():
            return m[:100]
    return None
